# Generated by Django 3.1.5 on 2026-03-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_moduleaccess_database'),
        ('programme_curriculum', '0032_auto_20260314_1649'),
        ('academic_information', '0002_auto_20260314_1649'),
        ('scholarships', '0002_mcmapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('RESEARCH', 'Research'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('INNOVATION', 'Innovation'), ('LEADERSHIP', 'Leadership'), ('COMMUNITY', 'Community Service')], max_length=20)),
                ('description', models.TextField()),
                ('criteria', models.TextField()),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certificate_provided', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_programmes', models.ManyToManyField(blank=True, related_name='awards', to='programme_curriculum.Programme')),
            ],
            options={
                'db_table': 'scholarships_award',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='programme_curriculum.batch')),
            ],
            options={
                'db_table': 'scholarships_meritlist',
                'ordering': ['-generated_date'],
                'unique_together': {('batch', 'academic_year', 'semester')},
            },
        ),
        migrations.AlterField(
            model_name='previous_winner',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MERIT', 'Merit-based'), ('NEED', 'Need-based'), ('CATEGORY', 'Category-based'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('RESEARCH', 'Research'), ('EXTERNAL', 'External / Government')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMESTER', 'Semester'), ('ANNUAL', 'Annual'), ('ONE_TIME', 'One-time')], max_length=20)),
                ('eligibility_criteria', models.TextField()),
                ('max_backlogs', models.IntegerField(default=0)),
                ('applicable_categories', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_batches', models.ManyToManyField(blank=True, related_name='scholarship_types', to='programme_curriculum.Batch')),
                ('applicable_programmes', models.ManyToManyField(blank=True, related_name='scholarship_types', to='programme_curriculum.Programme')),
            ],
            options={
                'db_table': 'scholarships_scholarshiptype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('category_at_application', models.CharField(max_length=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='scholarships/documents/')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scholarship_applications', to='globals.extrainfo')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarshiptype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='academic_information.student')),
            ],
            options={
                'db_table': 'scholarships_scholarshipapplication',
                'ordering': ['-application_date'],
                'unique_together': {('student', 'scholarship_type', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('merit_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scholarships.meritlist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_entries', to='academic_information.student')),
            ],
            options={
                'db_table': 'scholarships_meritlistentry',
                'ordering': ['rank'],
                'unique_together': {('merit_list', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AwardRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('award_date', models.DateField()),
                ('citation', models.TextField(blank=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='scholarships.award')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_given', to='globals.extrainfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to='academic_information.student')),
            ],
            options={
                'db_table': 'scholarships_awardrecipient',
                'ordering': ['-award_date'],
                'unique_together': {('award', 'student', 'academic_year')},
            },
        ),
    ]
