# Generated by Django manually
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_spac_scholarships'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiptype',
            name='cpi_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='scholarshiptype',
            name='annual_family_income_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='cpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='annual_family_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]