# Generated by Django 3.1.5 on 2026-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_scholarship_clarification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='clarification_document',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='clarification_requested',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='clarification_response',
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20),
        ),
    ]
