# Generated by Django 3.1.5 on 2026-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20260413_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
