# Generated by Django 3.1.5 on 2026-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_auto_20260418_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiptype',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
