# Generated by Django 3.1.5 on 2026-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_auto_20260419_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=30),
        ),
    ]
